"""Tests for scripts/update_cloudflare_real_ip.py."""

from __future__ import annotations

import os
import time
from unittest.mock import MagicMock, patch

import pytest
import requests

from scripts import update_cloudflare_real_ip as cfip

SAMPLE_IPV4 = ["173.245.48.0/20", "103.21.244.0/22"]
SAMPLE_IPV6 = ["2400:cb00::/32", "2606:4700::/32"]


def _seed_conf(path: str, ipv4=None, ipv6=None) -> None:
    ipv4 = ipv4 if ipv4 is not None else SAMPLE_IPV4
    ipv6 = ipv6 if ipv6 is not None else SAMPLE_IPV6
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(cfip.build_conf(ipv4, ipv6))


@pytest.fixture
def conf_paths(tmp_path, monkeypatch):
    conf = tmp_path / "pariah-cloudflare-ip.conf"
    backup = tmp_path / "pariah-cloudflare-ip.conf.bak"
    monkeypatch.setattr(cfip, "CONF_FILE", str(conf))
    monkeypatch.setattr(cfip, "BACKUP_FILE", str(backup))
    return conf, backup


def test_build_conf_includes_ranges_and_real_ip_header():
    content = cfip.build_conf(SAMPLE_IPV4, SAMPLE_IPV6)
    assert "set_real_ip_from 173.245.48.0/20;" in content
    assert "set_real_ip_from 2400:cb00::/32;" in content
    assert "real_ip_header CF-Connecting-IP;" in content
    assert content.strip().endswith("real_ip_header CF-Connecting-IP;")


def test_conf_directives_match_ignores_comment_and_timestamp_changes():
    older = (
        "# Auto-generated by update_cloudflare_real_ip.py\n"
        "# Last Updated: 2000-01-01 00:00:00 UTC\n"
        "\n"
        "set_real_ip_from 173.245.48.0/20;\n"
        "set_real_ip_from 2400:cb00::/32;\n"
        "real_ip_header CF-Connecting-IP;\n"
    )
    newer = cfip.build_conf(["173.245.48.0/20"], ["2400:cb00::/32"])
    assert cfip.conf_directives_match(older, newer)
    assert not cfip.conf_directives_match(
        older, cfip.build_conf(["1.2.3.0/24"], ["2400:cb00::/32"])
    )


def test_fetch_ip_list_parses_lines():
    fake = MagicMock()
    fake.text = "173.245.48.0/20\n\n103.21.244.0/22\n"
    fake.raise_for_status = MagicMock()
    with patch("scripts.update_cloudflare_real_ip.requests.get", return_value=fake):
        assert cfip.fetch_ip_list(cfip.IPV4_URL) == SAMPLE_IPV4


@patch("scripts.update_cloudflare_real_ip.run_cmd")
@patch("scripts.update_cloudflare_real_ip.fetch_ip_list")
def test_update_unchanged_refreshes_mtime_without_reload(
    mock_fetch, mock_run_cmd, conf_paths
):
    conf, _backup = conf_paths
    _seed_conf(str(conf))
    old_mtime = os.path.getmtime(conf)
    time.sleep(0.02)

    mock_fetch.side_effect = [SAMPLE_IPV4, SAMPLE_IPV6]

    assert cfip.update_cloudflare_real_ip() == 0
    assert os.path.getmtime(conf) >= old_mtime
    mock_run_cmd.assert_not_called()


@patch("scripts.update_cloudflare_real_ip.run_cmd")
@patch("scripts.update_cloudflare_real_ip.fetch_ip_list")
def test_update_writes_conf_and_reloads_nginx_on_change(
    mock_fetch, mock_run_cmd, conf_paths
):
    conf, backup = conf_paths
    _seed_conf(str(conf), ipv4=["1.1.1.0/24"], ipv6=["2001:db8::/32"])
    mock_fetch.side_effect = [SAMPLE_IPV4, SAMPLE_IPV6]
    mock_run_cmd.return_value = MagicMock(returncode=0, stdout="", stderr="")

    assert cfip.update_cloudflare_real_ip() == 0

    written = conf.read_text(encoding="utf-8")
    assert "set_real_ip_from 173.245.48.0/20;" in written
    assert "set_real_ip_from 2400:cb00::/32;" in written
    assert "real_ip_header CF-Connecting-IP;" in written
    assert backup.exists()
    assert "1.1.1.0/24" in backup.read_text(encoding="utf-8")

    assert mock_run_cmd.call_args_list[0].args[0] == ["nginx", "-t"]
    assert mock_run_cmd.call_args_list[1].args[0] == [
        "systemctl",
        "reload",
        "nginx",
    ]


@patch("scripts.update_cloudflare_real_ip.run_cmd")
@patch("scripts.update_cloudflare_real_ip.fetch_ip_list")
def test_update_restores_backup_when_nginx_t_fails(
    mock_fetch, mock_run_cmd, conf_paths
):
    conf, backup = conf_paths
    original = "set_real_ip_from 9.9.9.0/24;\nreal_ip_header CF-Connecting-IP;\n"
    conf.write_text(original, encoding="utf-8")

    mock_fetch.side_effect = [SAMPLE_IPV4, SAMPLE_IPV6]
    mock_run_cmd.return_value = MagicMock(
        returncode=1, stdout="", stderr="nginx: configuration file test failed"
    )

    assert cfip.update_cloudflare_real_ip() == 1
    assert conf.read_text(encoding="utf-8") == original
    assert backup.exists()
    mock_run_cmd.assert_called_once_with(["nginx", "-t"])


@patch("scripts.update_cloudflare_real_ip.fetch_ip_list")
def test_update_aborts_when_fetch_fails(mock_fetch, conf_paths):
    conf, _backup = conf_paths
    mock_fetch.side_effect = requests.ConnectionError("network down")

    assert cfip.update_cloudflare_real_ip() == 1
    assert not conf.exists()


@patch("scripts.update_cloudflare_real_ip.fetch_ip_list")
def test_update_aborts_when_ip_lists_empty(mock_fetch, conf_paths):
    conf, _backup = conf_paths
    mock_fetch.side_effect = [[], SAMPLE_IPV6]

    assert cfip.update_cloudflare_real_ip() == 1
    assert not conf.exists()
