#!/usr/bin/env python3
"""
Fetch Cloudflare published proxy ranges and refresh nginx real_ip config.

Writes /etc/nginx/conf.d/pariah-cloudflare-ip.conf, tests nginx syntax, and
reloads on change. Runs as root via pariah-cloudflare-ip.service.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from datetime import UTC, datetime

import requests

CONF_FILE = "/etc/nginx/conf.d/pariah-cloudflare-ip.conf"
BACKUP_FILE = f"{CONF_FILE}.bak"
IPV4_URL = "https://www.cloudflare.com/ips-v4"
IPV6_URL = "https://www.cloudflare.com/ips-v6"
FETCH_TIMEOUT = 30


def fetch_ip_list(url: str) -> list[str]:
    response = requests.get(url, timeout=FETCH_TIMEOUT)
    response.raise_for_status()
    return [line.strip() for line in response.text.splitlines() if line.strip()]


def build_conf(ipv4: list[str], ipv6: list[str]) -> str:
    updated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# Auto-generated by update_cloudflare_real_ip.py",
        f"# Last Updated: {updated}",
        "# Owned by OS Pariah Portal (pariah-cloudflare-ip.timer).",
        "",
        "# Cloudflare IPv4 ranges",
    ]
    lines.extend(f"set_real_ip_from {ip};" for ip in ipv4)
    lines.append("")
    lines.append("# Cloudflare IPv6 ranges")
    lines.extend(f"set_real_ip_from {ip};" for ip in ipv6)
    lines.append("")
    lines.append("# Trust the Cloudflare header for the real user IP")
    lines.append("real_ip_header CF-Connecting-IP;")
    lines.append("")
    return "\n".join(lines)


def non_comment_lines(text: str) -> list[str]:
    return [
        line
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def conf_directives_match(existing: str, new_content: str) -> bool:
    return non_comment_lines(existing) == non_comment_lines(new_content)


def run_cmd(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def update_cloudflare_real_ip() -> int:
    try:
        ipv4 = fetch_ip_list(IPV4_URL)
        ipv6 = fetch_ip_list(IPV6_URL)
    except requests.RequestException as exc:
        print(f"Error: Could not fetch Cloudflare IPs ({exc}). Aborting.")
        return 1

    if not ipv4 or not ipv6:
        print("Error: Cloudflare IP lists were empty. Aborting.")
        return 1

    new_content = build_conf(ipv4, ipv6)

    existing = ""
    if os.path.exists(CONF_FILE):
        with open(CONF_FILE, encoding="utf-8") as handle:
            existing = handle.read()

    if existing and conf_directives_match(existing, new_content):
        os.utime(CONF_FILE, None)
        print("Cloudflare real-IP ranges unchanged; conf timestamp refreshed.")
        return 0

    conf_dir = os.path.dirname(CONF_FILE)
    fd, tmp_path = tempfile.mkstemp(
        prefix="pariah-cloudflare-ip_", suffix=".conf", dir=conf_dir
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(new_content)
            handle.flush()
            os.fsync(handle.fileno())

        if os.path.exists(CONF_FILE):
            with open(CONF_FILE, "rb") as src, open(BACKUP_FILE, "wb") as dst:
                dst.write(src.read())

        os.replace(tmp_path, CONF_FILE)
        tmp_path = ""  # replaced; do not unlink in finally

        test = run_cmd(["nginx", "-t"])
        if test.returncode != 0:
            err = (test.stderr or test.stdout or "").strip()
            print(
                "Critical Error: nginx -t failed with new IPs. Restoring backup."
                + (f" ({err})" if err else "")
            )
            if os.path.exists(BACKUP_FILE):
                with open(BACKUP_FILE, "rb") as src, open(CONF_FILE, "wb") as dst:
                    dst.write(src.read())
            elif os.path.exists(CONF_FILE):
                os.remove(CONF_FILE)
            return 1

        reload = run_cmd(["systemctl", "reload", "nginx"])
        if reload.returncode != 0:
            err = (reload.stderr or reload.stdout or "").strip()
            print(
                "Error: Cloudflare IPs written but nginx reload failed."
                + (f" ({err})" if err else "")
            )
            return 1

        print("Success: Cloudflare IPs updated and nginx reloaded.")
        return 0
    finally:
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)


if __name__ == "__main__":
    sys.exit(update_cloudflare_real_ip())
