server {
    listen 80;
    listen [::]:80;
    server_name portal.example.com;

    return 301 https://portal.example.com$request_uri;
}

# A rate limiter for Portal to avoid DDOS attacks
limit_req_zone $binary_remote_addr zone=pariah_limit:10m rate=5r/s;

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    server_name portal.example.com;
    add_header Strict-Transport-Security "max-age=86400;" always;

    # Use Dummy certs until certbot is setup
    ssl_certificate /etc/nginx/dummypariah.crt; # Replace with real certs
    ssl_certificate_key /etc/nginx/dummypariah.key; # Replace with real certs
    #ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    #ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot

    #    Allow TLS version 1.2 only, which is a recommended default these days
    #    by international information security standards.
    ssl_protocols        TLSv1.2 TLSv1.3;

    ssl_session_cache    shared:SSL:10m;
    ssl_session_timeout  60m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    # Limit payload size for ticket attachments (e.g., 10MB)
    client_max_body_size 10M;

    #error_page  404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /srv/www/htdocs/;
    }

    location ~ /\.(?!well-known) {
    deny all;
    }
    location = /favicon.ico {
      log_not_found off;
      access_log off;
    }
    location = /robots.txt {
      allow all;
      log_not_found off;
      access_log off;
    }

    # Serve Static Files Directly (Bypasses Python completely for max speed)
    location /static/ {
        alias /opt/os_pariah/app/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Main Proxy Pass to Gunicorn
    location / {
        limit_req zone=pariah_limit burst=20 nodelay;
        proxy_pass http://unix:/run/os_pariah/pariah.sock;

        # CRITICAL HEADERS: Pass the real client IP to Python
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Give the portal time if Robust is responding slowly
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }

    # WebXML API (OpenSim Regions fetching config)
    location /regions/api/ {
        allow 192.168.1.1;      # Public IP of the Region Host
        allow 127.0.0.1;        # Localhost
        deny all;

        proxy_pass http://unix:/run/os_pariah/pariah.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}